In [1]:
import pandas as pd
import numpy as np

In [2]:
def ini_inspec(df):
    # Tamaño y estructura de los datos
    print("=== TAMAÑO Y ESTRUCTURA DE LOS DATOS ===")
    print(f"Número total de registros: {df.shape[0]}")
    print(f"Número de columnas: {df.shape[1]}")
    print(f"Uso de memoria: {df.memory_usage().sum() / 1024:.2f} KB")
    print("\n")

    # Tipos de datos y nombres de columnas
    print("=== TIPOS DE DATOS Y NOMBRES DE COLUMNAS ===")
    print(df.dtypes)
    print("\n")
    print("Información detallada del DataFrame:")
    print(df.info())
    print("\n")

    # Identificación de problemas iniciales
    print("=== IDENTIFICACIÓN DE PROBLEMAS INICIALES ===")
    print(f"Número de filas duplicadas: {df.duplicated().sum()}")
    print("\nValores nulos por columna:")
    print(df.isnull().sum())

    # Mostrar las primeras filas para verificar la estructura
    print("\nPrimeras filas del dataset:")
    print(df.head())

    # Mostrar las ultimas filas para verificar la estructura
    print("\nÚltimas filas del dataset:")
    print(df.tail(10))

In [41]:
#verifico con ejemplo si funciona
alimentos= pd.read_csv ('food_100.csv', index_col=0)

In [42]:
alimentos.axes[1]

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

In [43]:
alimentos.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df = alimentos.copy ()

In [49]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ini_inspec (df)

In [73]:
def crear_tabla_resumen(df):
    resumen = []
    #quiero crear un nuevo df con las columnas como filas, 
    for col in df.columns:
        # Extraer la información de cada columna del DF original
        tipo_dato = df[col].dtype
        categoria_dato = df[col].nunique()
        resumen.append({
            'Columna': col,
            'Tipo de dato': tipo_dato,
            'Categoría': categoria_dato
            })

    #Convertir el resumen en un DataFrame
    resumen_df = pd.DataFrame(resumen)
    return resumen_df.set_index('Columna')

In [74]:
crear_tabla_resumen(df)

                        Tipo de dato  Categoría
Columna
code                           int64        100
url                           object        100
creator                       object          6
created_t                      int64         47
created_datetime              object         47
...                              ...        ...
carbon-footprint_100g        float64          0
nutrition-score-fr_100g      float64         15
nutrition-score-uk_100g      float64         15
glycemic-index_100g          float64          0
water-hardness_100g          float64          0

[163 rows x 2 columns]