In [1]:
import pandas as pd
import numpy as hp
import os

In [ ]:
idMadridRS = pd.read_csv('Idealista Madrid Real State.csv')
idMadridRS.head()

In [9]:
df1=idMadridRS.copy()
df1

,Address,Price,Rooms,Squared_meters,Floor,Link,Summary,Distric,Type,Pool,Furniture,Exterior,Elevator
0,"calle Aguarón, Valdemarín, Madrid",900.0,NaN,55,2,www.idealista.com/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
1,"calle de Luisa Fernanda, Argüelles, Madrid",700.0,NaN,50,4,www.idealista.com/inmueble/91350410/,\nDisponible a principios de septiembre. Alqui...,Chamartin,Studio,False,False,False,True
2,"calle de Irún, Argüelles, Madrid",900.0,NaN,73,2,www.idealista.com/inmueble/98145156/,"\nExcelente estudio, junto a la estación de Pr...",Chamartin,Studio,False,False,True,True
3,"avenida del Doctor Federico Rubio y Galí, 88, ...",850.0,NaN,41,0,www.idealista.com/inmueble/98614584/,\nSe alquila estudio amueblado de 40 m2 recién...,Chamartin,Studio,False,True,True,True
4,"Valdemarín, Madrid",795.0,NaN,42,1,www.idealista.com/inmueble/97899849/,\nARAVACA-VALDEMARIN.\nExclusivo Loft de 40 M2...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,"calle de San Restituto, 53, Valdezarza, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/92066241/,"\nEstupendo piso amueblado, con cocina totalme...",Moncloa,Flat,False,True,True,True
513,"calle Arriaza, 12, Argüelles, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/29286956/,"\nPrecioso apartamento de un dormitorio, salón...",Moncloa,Flat,False,False,False,True
514,"Aravaca, Madrid",990.0,2.0,80,0,www.idealista.com/inmueble/96987552/,"\nAravaca, estupendo amplio apartamento de 2 d...",Moncloa,Flat,False,False,True,True
515,"Aravaca, Madrid",995.0,2.0,75,0,www.idealista.com/inmueble/98349774/,"\nOCASION, se alquila apartamento en Aravaca, ...",Moncloa,Flat,False,False,True,True
516,"Valdezarza, Madrid",750.0,1.0,50,6,www.idealista.com/inmueble/86380691/,"\n""OFERTA ""PUERTA DE HIERRO APARTAMENTO REFORM...",Moncloa,Flat,False,False,True,True

In [10]:
Madrid_idPL = pd.read_csv('Madrid idealista Property Listings.csv')
Madrid_idPL .head()

,url,listingUrl,title,id,price,baths,rooms,sqft,description,address,typology,advertiserProfessionalName,advertiserName
0,https://www.idealista.com/inmueble/104027174/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Villanueva,104027174,1920000,3,3,183,Residencia única con acabados de la más alta c...,"Recoletos, Madrid",Pisos,Promora Madrid,Promora Madrid
1,https://www.idealista.com/inmueble/102321942/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Núñez de Balboa,102321942,1995000,3,3,170,"Preciosa reforma a estrenar, con terrazas y ga...","Castellana, Madrid",Pisos,Madrid MMC,Engel & Völkers Madrid
2,https://www.idealista.com/inmueble/103334142/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Conde Orgaz-Piovera,103334142,1300000,3,4,270,DE SALAS CONSULTORES INMOBILIARIOS MAV02679 le...,"Hortaleza, Madrid",Pisos,De Salas Consultores Inmobiliarios,De Salas Consultores Inmobiliarios
3,https://www.idealista.com/inmueble/104161987/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Nueva España,104161987,1650000,3,3,248,Gilmar Real Estate vende espectacular piso en ...,"Chamartín, Madrid",Pisos,departamento comercial,Gilmar Viso - Chamartín
4,https://www.idealista.com/inmueble/103989666/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Claudio Coello,103989666,1590750,3,3,116,Descubre esta impresionante vivienda exterior ...,"Recoletos, Madrid",Pisos,Walter Haus Salamanca,Walter Haus Madrid

In [11]:
df2 = Madrid_idPL.copy()
df2

,url,listingUrl,title,id,price,baths,rooms,sqft,description,address,typology,advertiserProfessionalName,advertiserName
0,https://www.idealista.com/inmueble/104027174/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Villanueva,104027174,1920000,3,3,183,Residencia única con acabados de la más alta c...,"Recoletos, Madrid",Pisos,Promora Madrid,Promora Madrid
1,https://www.idealista.com/inmueble/102321942/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Núñez de Balboa,102321942,1995000,3,3,170,"Preciosa reforma a estrenar, con terrazas y ga...","Castellana, Madrid",Pisos,Madrid MMC,Engel & Völkers Madrid
2,https://www.idealista.com/inmueble/103334142/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Conde Orgaz-Piovera,103334142,1300000,3,4,270,DE SALAS CONSULTORES INMOBILIARIOS MAV02679 le...,"Hortaleza, Madrid",Pisos,De Salas Consultores Inmobiliarios,De Salas Consultores Inmobiliarios
3,https://www.idealista.com/inmueble/104161987/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Nueva España,104161987,1650000,3,3,248,Gilmar Real Estate vende espectacular piso en ...,"Chamartín, Madrid",Pisos,departamento comercial,Gilmar Viso - Chamartín
4,https://www.idealista.com/inmueble/103989666/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Claudio Coello,103989666,1590750,3,3,116,Descubre esta impresionante vivienda exterior ...,"Recoletos, Madrid",Pisos,Walter Haus Salamanca,Walter Haus Madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,https://www.idealista.com/inmueble/103960809/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de San Germán,103960809,1475000,4,5,376,Exclusiva vivienda en San GermánEngel & Völker...,"Cuzco-Castillejos, Madrid",Pisos,Madrid MMC - Tetuán y Fuencarral - S6,Engel & Völkers Madrid
911,https://www.idealista.com/inmueble/103494183/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Fuencarral,103494183,865000,2,2,127,"Esta magnífica vivienda, situada en una emblem...","Trafalgar, Madrid",Pisos,Walter Haus Madrid,Walter Haus Madrid
912,https://www.idealista.com/inmueble/102107584/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Castellana,102107584,7900000,5,4,473,"Álvora Capital Properties, consultora inmobili...","Barrio de Salamanca, Madrid",Pisos,álvora capital properties,álvora capital properties
913,https://www.idealista.com/inmueble/99991709/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Costillares,99991709,990000,4,6,293,Espacioso y tranquilo piso en Pinar de Chamart...,"Ciudad Lineal, Madrid",Pisos,Madrid MMC - Conde de Orgaz,Engel & Völkers Madrid
914,https://www.idealista.com/inmueble/103315777/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Cuatro Caminos,103315777,1080000,2,4,270,Única Inmobiliaria Chamartín ofrece esta gran ...,"Tetuán, Madrid",Pisos,Única Inmobiliaria Chamartin,Única Consultoría Inmobiliaria

In [12]:
id_Madrid = pd.read_csv('idealista Madrid.csv')
id_Madrid.head()

,url,listingUrl,title,id,price,baths,rooms,sqft,description,address,typology,advertiserProfessionalName,advertiserName
0,https://www.idealista.com/inmueble/104027174/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Villanueva,104027174,1920000,3,3,183,Residencia única con acabados de la más alta c...,"Recoletos, Madrid",Pisos,Promora Madrid,Promora Madrid
1,https://www.idealista.com/inmueble/102321942/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Núñez de Balboa,102321942,1995000,3,3,170,"Preciosa reforma a estrenar, con terrazas y ga...","Castellana, Madrid",Pisos,Madrid MMC,Engel & Völkers Madrid
2,https://www.idealista.com/inmueble/103334142/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Conde Orgaz-Piovera,103334142,1300000,3,4,270,DE SALAS CONSULTORES INMOBILIARIOS MAV02679 le...,"Hortaleza, Madrid",Pisos,De Salas Consultores Inmobiliarios,De Salas Consultores Inmobiliarios
3,https://www.idealista.com/inmueble/104161987/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Nueva España,104161987,1650000,3,3,248,Gilmar Real Estate vende espectacular piso en ...,"Chamartín, Madrid",Pisos,departamento comercial,Gilmar Viso - Chamartín
4,https://www.idealista.com/inmueble/103989666/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Claudio Coello,103989666,1590750,3,3,116,Descubre esta impresionante vivienda exterior ...,"Recoletos, Madrid",Pisos,Walter Haus Salamanca,Walter Haus Madrid

In [13]:
df3 = id_Madrid.copy()
df3

,url,listingUrl,title,id,price,baths,rooms,sqft,description,address,typology,advertiserProfessionalName,advertiserName
0,https://www.idealista.com/inmueble/104027174/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Villanueva,104027174,1920000,3,3,183,Residencia única con acabados de la más alta c...,"Recoletos, Madrid",Pisos,Promora Madrid,Promora Madrid
1,https://www.idealista.com/inmueble/102321942/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Núñez de Balboa,102321942,1995000,3,3,170,"Preciosa reforma a estrenar, con terrazas y ga...","Castellana, Madrid",Pisos,Madrid MMC,Engel & Völkers Madrid
2,https://www.idealista.com/inmueble/103334142/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Conde Orgaz-Piovera,103334142,1300000,3,4,270,DE SALAS CONSULTORES INMOBILIARIOS MAV02679 le...,"Hortaleza, Madrid",Pisos,De Salas Consultores Inmobiliarios,De Salas Consultores Inmobiliarios
3,https://www.idealista.com/inmueble/104161987/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Nueva España,104161987,1650000,3,3,248,Gilmar Real Estate vende espectacular piso en ...,"Chamartín, Madrid",Pisos,departamento comercial,Gilmar Viso - Chamartín
4,https://www.idealista.com/inmueble/103989666/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Claudio Coello,103989666,1590750,3,3,116,Descubre esta impresionante vivienda exterior ...,"Recoletos, Madrid",Pisos,Walter Haus Salamanca,Walter Haus Madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,https://www.idealista.com/inmueble/103960809/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de San Germán,103960809,1475000,4,5,376,Exclusiva vivienda en San GermánEngel & Völker...,"Cuzco-Castillejos, Madrid",Pisos,Madrid MMC - Tetuán y Fuencarral - S6,Engel & Völkers Madrid
911,https://www.idealista.com/inmueble/103494183/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Fuencarral,103494183,865000,2,2,127,"Esta magnífica vivienda, situada en una emblem...","Trafalgar, Madrid",Pisos,Walter Haus Madrid,Walter Haus Madrid
912,https://www.idealista.com/inmueble/102107584/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Castellana,102107584,7900000,5,4,473,"Álvora Capital Properties, consultora inmobili...","Barrio de Salamanca, Madrid",Pisos,álvora capital properties,álvora capital properties
913,https://www.idealista.com/inmueble/99991709/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Costillares,99991709,990000,4,6,293,Espacioso y tranquilo piso en Pinar de Chamart...,"Ciudad Lineal, Madrid",Pisos,Madrid MMC - Conde de Orgaz,Engel & Völkers Madrid
914,https://www.idealista.com/inmueble/103315777/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en Cuatro Caminos,103315777,1080000,2,4,270,Única Inmobiliaria Chamartín ofrece esta gran ...,"Tetuán, Madrid",Pisos,Única Inmobiliaria Chamartin,Única Consultoría Inmobiliaria

In [14]:
hp_Madrid = pd.read_csv('house_price_madrid_14_08_2022.csv')
hp_Madrid.head()

,price,house_type,house_type_2,rooms,m2,elevator,garage,neighborhood,district
0,495000,planta 1,exterior,3,118.0,True,True,Chopera,Arganzuela
1,485000,planta 2,exterior,2,82.0,True,True,Palos de Moguer,Arganzuela
2,315000,planta 2,exterior,2,72.0,False,False,Legazpi,Arganzuela
3,585000,planta 4,exterior,2,174.0,True,True,Palos de Moguer,Arganzuela
4,255000,bajo,exterior,3,75.0,False,False,Acacias,Arganzuela

In [15]:
df4 = hp_Madrid.copy()
df4

,price,house_type,house_type_2,rooms,m2,elevator,garage,neighborhood,district
0,495000,planta 1,exterior,3,118.0,True,True,Chopera,Arganzuela
1,485000,planta 2,exterior,2,82.0,True,True,Palos de Moguer,Arganzuela
2,315000,planta 2,exterior,2,72.0,False,False,Legazpi,Arganzuela
3,585000,planta 4,exterior,2,174.0,True,True,Palos de Moguer,Arganzuela
4,255000,bajo,exterior,3,75.0,False,False,Acacias,Arganzuela
...,...,...,...,...,...,...,...,...,...
15970,155000,planta 3,exterior,4,106.0,False,False,Villaverde Alto,villaverde
15971,108000,planta 3,exterior,3,60.0,False,False,San Cristóbal,villaverde
15972,140000,bajo,exterior,2,65.0,False,False,San Cristóbal,villaverde
15973,135000,planta 1,exterior,2,71.0,False,False,Los Rosales,villaverde
15974,150000,planta 4,exterior,4,71.0,True,False,San Cristóbal,villaverde

___________
voy a ver cual de todos los DF me interesa más para trabajarlo

In [17]:
df1.head(2)

,Address,Price,Rooms,Squared_meters,Floor,Link,Summary,Distric,Type,Pool,Furniture,Exterior,Elevator
0,"calle Aguarón, Valdemarín, Madrid",900.0,NaN,55,2,www.idealista.com/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
1,"calle de Luisa Fernanda, Argüelles, Madrid",700.0,NaN,50,4,www.idealista.com/inmueble/91350410/,\nDisponible a principios de septiembre. Alqui...,Chamartin,Studio,False,False,False,True

Este tiene precios de renta, no de compra, en principio, no me interesa.

In [ ]:
df2.head(2)

claramente me interesa más el DF1:
-tiene m2
-tiene columnas más 'trabajables': elevator, exterior

Pero no es de precio de venta del inmueble, sino de renta.

In [18]:
df3.head(2)

,url,listingUrl,title,id,price,baths,rooms,sqft,description,address,typology,advertiserProfessionalName,advertiserName
0,https://www.idealista.com/inmueble/104027174/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Villanueva,104027174,1920000,3,3,183,Residencia única con acabados de la más alta c...,"Recoletos, Madrid",Pisos,Promora Madrid,Promora Madrid
1,https://www.idealista.com/inmueble/102321942/,https://www.idealista.com/venta-viviendas/madr...,Piso en venta en calle de Núñez de Balboa,102321942,1995000,3,3,170,"Preciosa reforma a estrenar, con terrazas y ga...","Castellana, Madrid",Pisos,Madrid MMC,Engel & Völkers Madrid

In [19]:
df3.shape

(915, 13)

df3 es idéntico a df2

In [16]:
df4.head(2)

,price,house_type,house_type_2,rooms,m2,elevator,garage,neighborhood,district
0,495000,planta 1,exterior,3,118.0,True,True,Chopera,Arganzuela
1,485000,planta 2,exterior,2,82.0,True,True,Palos de Moguer,Arganzuela

In [20]:
df4.shape

(15975, 9)

Me voy a quedar con df2/3 porque:

-tiene el enlace
-tiene descripción que me permitirá buscar cosas de texto
-tiene la promotora que puede permitirme alguna hipotesis de qué vende cada una.
-tiene ID para ordenar